
workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20
      java: 17
    triggering:
      events:
        - push
      branches:
        - main
        - master
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build Web Project
        script: |
          npm run build
      - name: Add Android Platform
        script: |
          npx cap add android
      - name: Copy Web Assets to Native
        script: |
          npx cap copy android
      - name: Build Android APK (Debug)
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com # 修改为你的邮箱以接收 APK
