
workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
        - pattern: 'master'
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build Web Project
        script: |
          npm run build
      - name: Initialize Capacitor Android
        script: |
          npx cap telemetry off
          # 如果 android 目录不存在则添加，存在则直接同步
          if [ ! -d "android" ]; then
            npx cap add android
          fi
      - name: Sync Web Assets to Native
        script: |
          npx cap copy android
          npx cap sync android
      - name: Build Android APK (Debug)
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
